# Generated by Django 3.1.8 on 2021-04-21 14:07

from django.db import migrations, models
import django.db.models.deletion
import modules.core.blocks
import modules.core.models.snippets
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks
import wagtailnhsukfrontend.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0060_fix_workflow_unique_constraint"),
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "canonical_rel",
                    models.URLField(
                        blank=True,
                        help_text="If this article was first published elsewhere, put that link here to help SEO",
                        null=True,
                        verbose_name="Canonical link",
                    ),
                ),
                (
                    "fb_og_title",
                    models.CharField(
                        blank=True,
                        help_text="Facebook OG title - max 40 chars",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "fb_og_description",
                    models.CharField(
                        blank=True,
                        help_text="Facebook OG description - max 300 chars",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "twitter_card_title",
                    models.CharField(
                        blank=True,
                        help_text="Twitter card title - max 40 chars",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "twitter_card_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Twitter card image alt text - max 100 chars",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "twitter_card_description",
                    models.CharField(
                        blank=True,
                        help_text="Twitter card description - max 200 chars",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "rich_text",
                                wagtail.blocks.RichTextBlock(group=" Content"),
                            ),
                            (
                                "block_quote",
                                wagtail.blocks.BlockQuoteBlock(group=" Content"),
                            ),
                            ("embed", modules.core.blocks.EmbedBlock(group=" Content")),
                            (
                                "captioned_embed",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("embed", modules.core.blocks.EmbedBlock()),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "sub_title",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                    ],
                                    group=" Content",
                                ),
                            ),
                            (
                                "html_anchor",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "anchor",
                                            wagtail.blocks.CharBlock(
                                                help_text="Some where in the page you will need to add the anchor link to this ID. e.g. Use the 'rich text' block to add the anchor link",
                                                label="ID for anchor",
                                            ),
                                        )
                                    ],
                                    group=" Content",
                                ),
                            ),
                            (
                                "image",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "content_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=True
                                            ),
                                        ),
                                        (
                                            "alt_text",
                                            wagtail.blocks.CharBlock(
                                                help_text="Only leave this blank if the image is decorative.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "panel",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "heading_level",
                                            wagtail.blocks.IntegerBlock(
                                                default=3,
                                                help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.",
                                                max_value=6,
                                                min_value=2,
                                            ),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.RichTextBlock(
                                                required=True
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "promo",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "link_page",
                                            wagtail.blocks.PageChooserBlock(
                                                label="Page", required=False
                                            ),
                                        ),
                                        (
                                            "url",
                                            wagtail.blocks.URLBlock(
                                                label="URL", required=False
                                            ),
                                        ),
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                required=True
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "content_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Image", required=False
                                            ),
                                        ),
                                        (
                                            "alt_text",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "size",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("", "Default"),
                                                    ("small", "Small"),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "heading_level",
                                            wagtail.blocks.IntegerBlock(
                                                default=3,
                                                help_text="The heading level affects users with screen readers. Default=3, Min=2, Max=4.",
                                                max_value=4,
                                                min_value=2,
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "expander",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                required=True
                                            ),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "richtext",
                                                        wagtail.blocks.RichTextBlock(),
                                                    ),
                                                    (
                                                        "action_link",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "text",
                                                                    wagtail.blocks.CharBlock(
                                                                        label="Link text",
                                                                        required=True,
                                                                    ),
                                                                ),
                                                                (
                                                                    "external_url",
                                                                    wagtail.blocks.URLBlock(
                                                                        label="URL",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "new_window",
                                                                    wagtail.blocks.BooleanBlock(
                                                                        label="Open in new window",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "internal_page",
                                                                    wagtail.blocks.PageChooserBlock(
                                                                        label="Internal Page",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "inset_text",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "body",
                                                                    wagtail.blocks.RichTextBlock(
                                                                        required=True
                                                                    ),
                                                                )
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "image",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "content_image",
                                                                    wagtail.images.blocks.ImageChooserBlock(
                                                                        required=True
                                                                    ),
                                                                ),
                                                                (
                                                                    "alt_text",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text="Only leave this blank if the image is decorative.",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "caption",
                                                                    wagtail.blocks.CharBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "grey_panel",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "label",
                                                                    wagtail.blocks.CharBlock(
                                                                        label="heading",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "heading_level",
                                                                    wagtail.blocks.IntegerBlock(
                                                                        default=3,
                                                                        help_text="The heading level affects users with screen readers. Ignore this if there is no heading. Default=3, Min=2, Max=6.",
                                                                        max_value=6,
                                                                        min_value=2,
                                                                    ),
                                                                ),
                                                                (
                                                                    "body",
                                                                    wagtail.blocks.RichTextBlock(
                                                                        required=True
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "feature_card",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "feature_heading",
                                                                    wagtail.blocks.CharBlock(
                                                                        required=True
                                                                    ),
                                                                ),
                                                                (
                                                                    "heading_level",
                                                                    wagtail.blocks.IntegerBlock(
                                                                        default=3,
                                                                        help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.",
                                                                        max_value=6,
                                                                        min_value=2,
                                                                    ),
                                                                ),
                                                                (
                                                                    "heading_size",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "",
                                                                                "Default",
                                                                            ),
                                                                            (
                                                                                "small",
                                                                                "Small",
                                                                            ),
                                                                            (
                                                                                "medium",
                                                                                "Medium",
                                                                            ),
                                                                            (
                                                                                "large",
                                                                                "Large",
                                                                            ),
                                                                        ],
                                                                        help_text="The heading size affects the visual size, this follows the front-end library's sizing.",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "body",
                                                                    wagtail.blocks.RichTextBlock(
                                                                        required=True
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "warning_callout",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "title",
                                                                    wagtail.blocks.CharBlock(
                                                                        default="Important",
                                                                        required=True,
                                                                    ),
                                                                ),
                                                                (
                                                                    "visually_hidden_prefix",
                                                                    wagtail.blocks.BooleanBlock(
                                                                        help_text='If the title doesn\'t contain the word "Important" select this to add a visually hidden "Important", to aid screen readers.',
                                                                        label="Visually hidden prefix",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "heading_level",
                                                                    wagtail.blocks.IntegerBlock(
                                                                        default=3,
                                                                        help_text="The heading level affects users with screen readers. Default=3, Min=2, Max=6.",
                                                                        max_value=6,
                                                                        min_value=2,
                                                                        required=True,
                                                                    ),
                                                                ),
                                                                (
                                                                    "body",
                                                                    wagtail.blocks.RichTextBlock(
                                                                        required=True
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "summary_list",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "rows",
                                                                    wagtail.blocks.ListBlock(
                                                                        wagtailnhsukfrontend.blocks.SummaryListRowBlock
                                                                    ),
                                                                ),
                                                                (
                                                                    "no_border",
                                                                    wagtail.blocks.BooleanBlock(
                                                                        default=False,
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "table",
                                                        modules.core.blocks.TableBlock(),
                                                    ),
                                                ],
                                                required=True,
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "grey_panel",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.CharBlock(
                                                label="heading", required=False
                                            ),
                                        ),
                                        (
                                            "heading_level",
                                            wagtail.blocks.IntegerBlock(
                                                default=3,
                                                help_text="The heading level affects users with screen readers. Ignore this if there is no heading. Default=3, Min=2, Max=6.",
                                                max_value=6,
                                                min_value=2,
                                            ),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.RichTextBlock(
                                                required=True
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "inset_text",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "body",
                                            wagtail.blocks.RichTextBlock(
                                                required=True
                                            ),
                                        )
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "panel_list",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "panels",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "left_panel",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "label",
                                                                        wagtail.blocks.CharBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "heading_level",
                                                                        wagtail.blocks.IntegerBlock(
                                                                            default=3,
                                                                            help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.",
                                                                            max_value=6,
                                                                            min_value=2,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "body",
                                                                        wagtail.blocks.RichTextBlock(
                                                                            required=True
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "right_panel",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "label",
                                                                        wagtail.blocks.CharBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "heading_level",
                                                                        wagtail.blocks.IntegerBlock(
                                                                            default=3,
                                                                            help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.",
                                                                            max_value=6,
                                                                            min_value=2,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "body",
                                                                        wagtail.blocks.RichTextBlock(
                                                                            required=True
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        )
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "promo_group",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "column",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("one-half", "One-half"),
                                                    ("one-third", "One-third"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "size",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("", "Default"),
                                                    ("small", "Small"),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "heading_level",
                                            wagtail.blocks.IntegerBlock(
                                                default=3,
                                                help_text="The heading level affects users with screen readers. Default=3, Min=2, Max=4.",
                                                max_value=4,
                                                min_value=2,
                                            ),
                                        ),
                                        (
                                            "promos",
                                            wagtail.blocks.ListBlock(
                                                modules.core.blocks.BasePromoBlock
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "warning_callout",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                default="Important", required=True
                                            ),
                                        ),
                                        (
                                            "visually_hidden_prefix",
                                            wagtail.blocks.BooleanBlock(
                                                help_text='If the title doesn\'t contain the word "Important" select this to add a visually hidden "Important", to aid screen readers.',
                                                label="Visually hidden prefix",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "heading_level",
                                            wagtail.blocks.IntegerBlock(
                                                default=3,
                                                help_text="The heading level affects users with screen readers. Default=3, Min=2, Max=6.",
                                                max_value=6,
                                                min_value=2,
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.RichTextBlock(
                                                required=True
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "table",
                                modules.core.blocks.TableBlock(group=" NHS Components"),
                            ),
                            (
                                "panel_table",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("title", wagtail.blocks.CharBlock()),
                                        ("table", modules.core.blocks.TableBlock()),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "action_link",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "text",
                                            wagtail.blocks.CharBlock(
                                                label="Link text", required=True
                                            ),
                                        ),
                                        (
                                            "external_url",
                                            wagtail.blocks.URLBlock(
                                                label="URL", required=False
                                            ),
                                        ),
                                        (
                                            "new_window",
                                            wagtail.blocks.BooleanBlock(
                                                label="Open in new window",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "internal_page",
                                            wagtail.blocks.PageChooserBlock(
                                                label="Internal Page", required=False
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "legal_information",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "legal_information",
                                            wagtail.snippets.blocks.SnippetChooserBlock(
                                                modules.core.models.snippets.LegalInformation
                                            ),
                                        )
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "newsletter_signup",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                required=True
                                            ),
                                        ),
                                        (
                                            "heading_level",
                                            wagtail.blocks.IntegerBlock(
                                                default=3,
                                                help_text="The heading level affects users with screen readers. Default=3, Min=2, Max=4.",
                                                max_value=4,
                                                min_value=2,
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "mailing_list_id",
                                            wagtail.blocks.CharBlock(
                                                required=True
                                            ),
                                        ),
                                    ],
                                    group=" Content",
                                ),
                            ),
                        ],
                        blank=True,
                        verbose_name="Body blocks",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Updated at (leave blank for initial publication)",
                    ),
                ),
                (
                    "history",
                    wagtail.fields.RichTextField(
                        blank=True,
                        verbose_name="Version history (leave blank for initial publication)",
                    ),
                ),
                (
                    "fb_og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facebook OG image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.nhsximage",
                    ),
                ),
                (
                    "twitter_card_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Twitter card image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.nhsximage",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="PublicationIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "fb_og_title",
                    models.CharField(
                        blank=True,
                        help_text="Facebook OG title - max 40 chars",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "fb_og_description",
                    models.CharField(
                        blank=True,
                        help_text="Facebook OG description - max 300 chars",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "twitter_card_title",
                    models.CharField(
                        blank=True,
                        help_text="Twitter card title - max 40 chars",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "twitter_card_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Twitter card image alt text - max 100 chars",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "twitter_card_description",
                    models.CharField(
                        blank=True,
                        help_text="Twitter card description - max 200 chars",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("sub_head", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "rich_text",
                                wagtail.blocks.RichTextBlock(group=" Content"),
                            ),
                            (
                                "block_quote",
                                wagtail.blocks.BlockQuoteBlock(group=" Content"),
                            ),
                            ("embed", modules.core.blocks.EmbedBlock(group=" Content")),
                            (
                                "captioned_embed",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("embed", modules.core.blocks.EmbedBlock()),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "sub_title",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                    ],
                                    group=" Content",
                                ),
                            ),
                            (
                                "html_anchor",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "anchor",
                                            wagtail.blocks.CharBlock(
                                                help_text="Some where in the page you will need to add the anchor link to this ID. e.g. Use the 'rich text' block to add the anchor link",
                                                label="ID for anchor",
                                            ),
                                        )
                                    ],
                                    group=" Content",
                                ),
                            ),
                            (
                                "image",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "content_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=True
                                            ),
                                        ),
                                        (
                                            "alt_text",
                                            wagtail.blocks.CharBlock(
                                                help_text="Only leave this blank if the image is decorative.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "panel",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "heading_level",
                                            wagtail.blocks.IntegerBlock(
                                                default=3,
                                                help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.",
                                                max_value=6,
                                                min_value=2,
                                            ),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.RichTextBlock(
                                                required=True
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "promo",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "link_page",
                                            wagtail.blocks.PageChooserBlock(
                                                label="Page", required=False
                                            ),
                                        ),
                                        (
                                            "url",
                                            wagtail.blocks.URLBlock(
                                                label="URL", required=False
                                            ),
                                        ),
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                required=True
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "content_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Image", required=False
                                            ),
                                        ),
                                        (
                                            "alt_text",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "size",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("", "Default"),
                                                    ("small", "Small"),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "heading_level",
                                            wagtail.blocks.IntegerBlock(
                                                default=3,
                                                help_text="The heading level affects users with screen readers. Default=3, Min=2, Max=4.",
                                                max_value=4,
                                                min_value=2,
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "expander",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                required=True
                                            ),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "richtext",
                                                        wagtail.blocks.RichTextBlock(),
                                                    ),
                                                    (
                                                        "action_link",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "text",
                                                                    wagtail.blocks.CharBlock(
                                                                        label="Link text",
                                                                        required=True,
                                                                    ),
                                                                ),
                                                                (
                                                                    "external_url",
                                                                    wagtail.blocks.URLBlock(
                                                                        label="URL",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "new_window",
                                                                    wagtail.blocks.BooleanBlock(
                                                                        label="Open in new window",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "internal_page",
                                                                    wagtail.blocks.PageChooserBlock(
                                                                        label="Internal Page",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "inset_text",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "body",
                                                                    wagtail.blocks.RichTextBlock(
                                                                        required=True
                                                                    ),
                                                                )
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "image",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "content_image",
                                                                    wagtail.images.blocks.ImageChooserBlock(
                                                                        required=True
                                                                    ),
                                                                ),
                                                                (
                                                                    "alt_text",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text="Only leave this blank if the image is decorative.",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "caption",
                                                                    wagtail.blocks.CharBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "grey_panel",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "label",
                                                                    wagtail.blocks.CharBlock(
                                                                        label="heading",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "heading_level",
                                                                    wagtail.blocks.IntegerBlock(
                                                                        default=3,
                                                                        help_text="The heading level affects users with screen readers. Ignore this if there is no heading. Default=3, Min=2, Max=6.",
                                                                        max_value=6,
                                                                        min_value=2,
                                                                    ),
                                                                ),
                                                                (
                                                                    "body",
                                                                    wagtail.blocks.RichTextBlock(
                                                                        required=True
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "feature_card",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "feature_heading",
                                                                    wagtail.blocks.CharBlock(
                                                                        required=True
                                                                    ),
                                                                ),
                                                                (
                                                                    "heading_level",
                                                                    wagtail.blocks.IntegerBlock(
                                                                        default=3,
                                                                        help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.",
                                                                        max_value=6,
                                                                        min_value=2,
                                                                    ),
                                                                ),
                                                                (
                                                                    "heading_size",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "",
                                                                                "Default",
                                                                            ),
                                                                            (
                                                                                "small",
                                                                                "Small",
                                                                            ),
                                                                            (
                                                                                "medium",
                                                                                "Medium",
                                                                            ),
                                                                            (
                                                                                "large",
                                                                                "Large",
                                                                            ),
                                                                        ],
                                                                        help_text="The heading size affects the visual size, this follows the front-end library's sizing.",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "body",
                                                                    wagtail.blocks.RichTextBlock(
                                                                        required=True
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "warning_callout",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "title",
                                                                    wagtail.blocks.CharBlock(
                                                                        default="Important",
                                                                        required=True,
                                                                    ),
                                                                ),
                                                                (
                                                                    "visually_hidden_prefix",
                                                                    wagtail.blocks.BooleanBlock(
                                                                        help_text='If the title doesn\'t contain the word "Important" select this to add a visually hidden "Important", to aid screen readers.',
                                                                        label="Visually hidden prefix",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "heading_level",
                                                                    wagtail.blocks.IntegerBlock(
                                                                        default=3,
                                                                        help_text="The heading level affects users with screen readers. Default=3, Min=2, Max=6.",
                                                                        max_value=6,
                                                                        min_value=2,
                                                                        required=True,
                                                                    ),
                                                                ),
                                                                (
                                                                    "body",
                                                                    wagtail.blocks.RichTextBlock(
                                                                        required=True
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "summary_list",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "rows",
                                                                    wagtail.blocks.ListBlock(
                                                                        wagtailnhsukfrontend.blocks.SummaryListRowBlock
                                                                    ),
                                                                ),
                                                                (
                                                                    "no_border",
                                                                    wagtail.blocks.BooleanBlock(
                                                                        default=False,
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "table",
                                                        modules.core.blocks.TableBlock(),
                                                    ),
                                                ],
                                                required=True,
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "grey_panel",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.CharBlock(
                                                label="heading", required=False
                                            ),
                                        ),
                                        (
                                            "heading_level",
                                            wagtail.blocks.IntegerBlock(
                                                default=3,
                                                help_text="The heading level affects users with screen readers. Ignore this if there is no heading. Default=3, Min=2, Max=6.",
                                                max_value=6,
                                                min_value=2,
                                            ),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.RichTextBlock(
                                                required=True
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "inset_text",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "body",
                                            wagtail.blocks.RichTextBlock(
                                                required=True
                                            ),
                                        )
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "panel_list",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "panels",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "left_panel",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "label",
                                                                        wagtail.blocks.CharBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "heading_level",
                                                                        wagtail.blocks.IntegerBlock(
                                                                            default=3,
                                                                            help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.",
                                                                            max_value=6,
                                                                            min_value=2,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "body",
                                                                        wagtail.blocks.RichTextBlock(
                                                                            required=True
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "right_panel",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "label",
                                                                        wagtail.blocks.CharBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "heading_level",
                                                                        wagtail.blocks.IntegerBlock(
                                                                            default=3,
                                                                            help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.",
                                                                            max_value=6,
                                                                            min_value=2,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "body",
                                                                        wagtail.blocks.RichTextBlock(
                                                                            required=True
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        )
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "promo_group",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "column",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("one-half", "One-half"),
                                                    ("one-third", "One-third"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "size",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("", "Default"),
                                                    ("small", "Small"),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "heading_level",
                                            wagtail.blocks.IntegerBlock(
                                                default=3,
                                                help_text="The heading level affects users with screen readers. Default=3, Min=2, Max=4.",
                                                max_value=4,
                                                min_value=2,
                                            ),
                                        ),
                                        (
                                            "promos",
                                            wagtail.blocks.ListBlock(
                                                modules.core.blocks.BasePromoBlock
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "warning_callout",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                default="Important", required=True
                                            ),
                                        ),
                                        (
                                            "visually_hidden_prefix",
                                            wagtail.blocks.BooleanBlock(
                                                help_text='If the title doesn\'t contain the word "Important" select this to add a visually hidden "Important", to aid screen readers.',
                                                label="Visually hidden prefix",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "heading_level",
                                            wagtail.blocks.IntegerBlock(
                                                default=3,
                                                help_text="The heading level affects users with screen readers. Default=3, Min=2, Max=6.",
                                                max_value=6,
                                                min_value=2,
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.RichTextBlock(
                                                required=True
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "table",
                                modules.core.blocks.TableBlock(group=" NHS Components"),
                            ),
                            (
                                "panel_table",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("title", wagtail.blocks.CharBlock()),
                                        ("table", modules.core.blocks.TableBlock()),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "action_link",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "text",
                                            wagtail.blocks.CharBlock(
                                                label="Link text", required=True
                                            ),
                                        ),
                                        (
                                            "external_url",
                                            wagtail.blocks.URLBlock(
                                                label="URL", required=False
                                            ),
                                        ),
                                        (
                                            "new_window",
                                            wagtail.blocks.BooleanBlock(
                                                label="Open in new window",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "internal_page",
                                            wagtail.blocks.PageChooserBlock(
                                                label="Internal Page", required=False
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "legal_information",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "legal_information",
                                            wagtail.snippets.blocks.SnippetChooserBlock(
                                                modules.core.models.snippets.LegalInformation
                                            ),
                                        )
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "newsletter_signup",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                required=True
                                            ),
                                        ),
                                        (
                                            "heading_level",
                                            wagtail.blocks.IntegerBlock(
                                                default=3,
                                                help_text="The heading level affects users with screen readers. Default=3, Min=2, Max=4.",
                                                max_value=4,
                                                min_value=2,
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "mailing_list_id",
                                            wagtail.blocks.CharBlock(
                                                required=True
                                            ),
                                        ),
                                    ],
                                    group=" Content",
                                ),
                            ),
                        ],
                        blank=True,
                        verbose_name="Body blocks",
                    ),
                ),
                (
                    "fb_og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facebook OG image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.nhsximage",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publicationindexpage_hero_image",
                        to="images.nhsximage",
                    ),
                ),
                (
                    "twitter_card_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Twitter card image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.nhsximage",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page", models.Model),
        ),
    ]
