# Generated by Django 3.1.8 on 2021-04-20 15:21

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    replaces = [('longform', '0002_longformpost_last_edited'), ('longform', '0003_auto_20210420_1431'), ('longform', '0004_longformpost_history')]

    dependencies = [
        ('longform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='longformpost',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated at (leave blank for initial publication)'),
        ),
        migrations.AddField(
            model_name='longformpost',
            name='history',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Version history (leave blank for initial publication)'),
        ),
    ]
