# Generated by Django 3.1.8 on 2021-04-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("longform", "0002_auto_20210420_1557"),
    ]

    operations = [
        migrations.RemoveField(model_name="longformpost", name="authors",),
    ]
