# Generated by Django 3.0.4 on 2020-04-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_posts", "0005_auto_20200406_0753"),
        ("blog_posts", "0006_blogpost_authors"),
    ]

    operations = []
