# Generated by Django 3.0.4 on 2020-04-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0008_auto_20200407_1438'),
        ('blog_posts', '0008_auto_20200407_1448'),
    ]

    operations = [
    ]
