# Generated by Django 3.0.4 on 2020-04-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0014_auto_20200409_1210'),
        ('blog_posts', '0014_remove_blogpostindexpage_headline'),
    ]

    operations = [
    ]
