# Generated by Django 3.0.4 on 2020-04-15 11:07

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog_posts", "0019_auto_20200415_1014"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpostindexpage",
            name="featured_posts",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.blocks.PageChooserBlock(
                            label="Page",
                            page_type=["blog_posts.BlogPost"],
                            required=True,
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
