# Generated by Django 3.0.4 on 2020-09-01 11:07

import datetime
from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("meeting_minutes", "0002_meetingminuteslistingpage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meetingminutes", old_name="meeting_time", new_name="start_time",
        ),
        migrations.AddField(
            model_name="meetingminutes",
            name="end_time",
            field=models.TimeField(default=datetime.time(11, 7, 19, 378976)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meetingminutes",
            name="venue",
            field=models.CharField(
                default=datetime.time(11, 7, 24, 221853), max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="meetingminutes",
            name="apologies",
            field=wagtail.fields.StreamField(
                [
                    (
                        "person",
                        wagtail.blocks.StructBlock(
                            [
                                ("name", wagtail.blocks.CharBlock(required=True)),
                                (
                                    "organisation",
                                    wagtail.blocks.CharBlock(required=True),
                                ),
                                ("role", wagtail.blocks.CharBlock(required=True)),
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                            ]
                        ),
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="meetingminutes",
            name="attendees",
            field=wagtail.fields.StreamField(
                [
                    (
                        "person",
                        wagtail.blocks.StructBlock(
                            [
                                ("name", wagtail.blocks.CharBlock(required=True)),
                                (
                                    "organisation",
                                    wagtail.blocks.CharBlock(required=True),
                                ),
                                ("role", wagtail.blocks.CharBlock(required=True)),
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                            ]
                        ),
                    )
                ]
            ),
        ),
    ]
