# Generated by Django 3.0.4 on 2020-04-06 07:49

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        ("core", "0007_auto_20200402_1310"),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='NavigationSettings',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('primary', wagtail.core.fields.StreamField([('page', wagtail.core.blocks.StructBlock([('link_page', wagtail.core.blocks.PageChooserBlock(required=True)), ('title_override', wagtail.core.blocks.CharBlock(required=False))]))], blank=True)),
        #         ('footer', wagtail.core.fields.StreamField([('page', wagtail.core.blocks.StructBlock([('link_page', wagtail.core.blocks.PageChooserBlock(required=True)), ('title_override', wagtail.core.blocks.CharBlock(required=False))]))], blank=True)),
        #         ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
        #     ],
        #     options={
        #         'abstract': False,
        #     },
        # ),
    ]
