# Generated by Django 3.0.4 on 2020-04-03 14:32

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20200402_1310"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="automatic",
            field=models.BooleanField(
                default=False, help_text="Build automatically from sibling pages"
            ),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="sidebar_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "page",
                        wagtail.blocks.PageChooserBlock(
                            label="Linked Page", required=True
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
