# Generated by Django 3.0.4 on 2020-04-03 15:03

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20200403_1432"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="sidebar_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "link",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "link_page",
                                                wagtail.blocks.PageChooserBlock(
                                                    label="Page", required=False
                                                ),
                                            ),
                                            (
                                                "link_document",
                                                wagtail.documents.blocks.DocumentChooserBlock(
                                                    label="Document", required=False
                                                ),
                                            ),
                                            (
                                                "link_external",
                                                wagtail.blocks.URLBlock(
                                                    label="URL", required=False
                                                ),
                                            ),
                                        ],
                                        label="Link to (choose one)",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
