# Generated by Django 3.0.4 on 2020-04-06 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200403_1503'),
        ('core', '0008_navigationsettings'),
    ]

    operations = [
    ]
