# Generated by Django 3.0.4 on 2020-04-07 14:48

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_merge_20200406_0829"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articlepage", old_name="sidebar_links", new_name="page_links",
        ),
        migrations.AddField(
            model_name="sectionpage",
            name="automatic",
            field=models.BooleanField(
                default=False, help_text="Build automatically from sibling pages"
            ),
        ),
        migrations.AddField(
            model_name="sectionpage",
            name="page_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "link",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "link_page",
                                                wagtail.blocks.PageChooserBlock(
                                                    label="Page", required=False
                                                ),
                                            ),
                                            (
                                                "link_document",
                                                wagtail.documents.blocks.DocumentChooserBlock(
                                                    label="Document", required=False
                                                ),
                                            ),
                                            (
                                                "link_external",
                                                wagtail.blocks.URLBlock(
                                                    label="URL", required=False
                                                ),
                                            ),
                                        ],
                                        label="Link to (choose one)",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
