# Generated by Django 3.0.4 on 2020-04-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20200406_0829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavigationSettings',
        ),
    ]
