# Generated by Django 3.0.4 on 2020-04-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_auto_20200407_1448"),
    ]

    # operations = [
    #     migrations.DeleteModel(
    #         name='NavigationSettings',
    #     ),
    # ]
