# Generated by Django 3.0.4 on 2020-04-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200408_1201'),
        ('core', '0012_delete_navigationsettings'),
    ]

    operations = [
    ]
