# Generated by Django 3.0.4 on 2020-04-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_remove_sectionpage_headline"),
        ("core", "0017_auto_20200409_1210"),
    ]

    operations = []
