# Generated by Django 3.0.4 on 2020-04-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_merge_20200409_1317"),
        ("core", "0018_merge_20200409_1245"),
    ]

    operations = []
