# Generated by Django 3.0.4 on 2020-04-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_merge_20200409_1317"),
    ]

    operations = [
        migrations.CreateModel(
            name="CookieFormPage",
            fields=[
                (
                    "articlepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.ArticlePage",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("core.articlepage",),
        ),
    ]
