# Generated by Django 3.0.4 on 2020-04-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_cookieformpage"),
        ("core", "0020_auto_20200409_1414"),
    ]

    operations = []
