# Generated by Django 3.0.4 on 2020-04-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_auto_20200409_1452"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionpage",
            name="automatic",
            field=models.BooleanField(
                default=False, help_text="Build automatically from child pages"
            ),
        ),
    ]
