# Generated by Django 3.0.4 on 2020-04-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_auto_20200414_0913"),
        ("core", "0023_auto_20200409_1453"),
    ]

    operations = []
