# Generated by Django 3.0.4 on 2020-08-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_auto_20200828_0924"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionpage",
            name="page_width",
            field=models.CharField(
                choices=[("two-thirds", "Two Thirds"), ("full", "Full")],
                default="two-thirds",
                max_length=20,
            ),
        ),
    ]
