# Generated by Django 3.0.7 on 2020-09-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200924_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='site_name',
            field=models.CharField(blank=True, help_text='The name of the website which will be associated with some social media shares', max_length=255, null=True),
        ),
    ]
