# Generated by Django 3.2.16 on 2022-11-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20210902_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssettings',
            name='ga4_id',
            field=models.CharField(blank=True, help_text='GA4 ID', max_length=25, null=True),
        ),
    ]
