# Generated by Django 3.0.7 on 2020-11-12 08:52

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import modules.core.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks
import wagtail.images.blocks
import wagtailnhsukfrontend.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStudyPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "sidebar_title",
                    models.CharField(
                        blank=True,
                        default="Related Pages",
                        help_text="The title to appear above the links in the sidebar",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "page_links",
                    wagtail.fields.StreamField(
                        [
                            (
                                "link",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "link",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "link_page",
                                                        wagtail.blocks.PageChooserBlock(
                                                            label="Page", required=False
                                                        ),
                                                    ),
                                                    (
                                                        "link_document",
                                                        wagtail.documents.blocks.DocumentChooserBlock(
                                                            label="Document",
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "link_external",
                                                        wagtail.blocks.URLBlock(
                                                            label="URL", required=False
                                                        ),
                                                    ),
                                                ],
                                                label="Link to (choose one)",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                    ),
                ),
                (
                    "automatic",
                    models.BooleanField(
                        default=False,
                        help_text="Build automatically from sibling pages",
                    ),
                ),
                (
                    "fb_og_title",
                    models.CharField(
                        blank=True,
                        help_text="Facebook OG title - max 40 chars",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "fb_og_description",
                    models.CharField(
                        blank=True,
                        help_text="Facebook OG description - max 300 chars",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "twitter_card_title",
                    models.CharField(
                        blank=True,
                        help_text="Twitter card title - max 40 chars",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "twitter_card_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Twitter card image alt text - max 100 chars",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "twitter_card_description",
                    models.CharField(
                        blank=True,
                        help_text="Twitter card description - max 200 chars",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("sub_head", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "rich_text",
                                wagtail.blocks.RichTextBlock(group=" Content"),
                            ),
                            (
                                "block_quote",
                                wagtail.blocks.BlockQuoteBlock(group=" Content"),
                            ),
                            ("embed", modules.core.blocks.EmbedBlock(group=" Content")),
                            (
                                "captioned_embed",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("embed", modules.core.blocks.EmbedBlock()),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "sub_title",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                    ],
                                    group=" Content",
                                ),
                            ),
                            (
                                "image",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "content_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=True
                                            ),
                                        ),
                                        (
                                            "alt_text",
                                            wagtail.blocks.CharBlock(
                                                help_text="Only leave this blank if the image is decorative.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "panel",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "heading_level",
                                            wagtail.blocks.IntegerBlock(
                                                default=3,
                                                help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=4.",
                                                max_value=4,
                                                min_value=2,
                                            ),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.RichTextBlock(
                                                required=True
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "promo",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "link_page",
                                            wagtail.blocks.PageChooserBlock(
                                                label="Page", required=False
                                            ),
                                        ),
                                        (
                                            "url",
                                            wagtail.blocks.URLBlock(
                                                label="URL", required=False
                                            ),
                                        ),
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                required=True
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "content_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Image", required=False
                                            ),
                                        ),
                                        (
                                            "alt_text",
                                            wagtail.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "size",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("", "Default"),
                                                    ("small", "Small"),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "heading_level",
                                            wagtail.blocks.IntegerBlock(
                                                default=3,
                                                help_text="The heading level affects users with screen readers. Default=3, Min=2, Max=4.",
                                                max_value=4,
                                                min_value=2,
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "expander",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                required=True
                                            ),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "richtext",
                                                        wagtail.blocks.RichTextBlock(),
                                                    ),
                                                    (
                                                        "action_link",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "text",
                                                                    wagtail.blocks.CharBlock(
                                                                        label="Link text",
                                                                        required=True,
                                                                    ),
                                                                ),
                                                                (
                                                                    "external_url",
                                                                    wagtail.blocks.URLBlock(
                                                                        label="URL",
                                                                        required=True,
                                                                    ),
                                                                ),
                                                                (
                                                                    "new_window",
                                                                    wagtail.blocks.BooleanBlock(
                                                                        label="Open in new window",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "inset_text",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "body",
                                                                    wagtail.blocks.RichTextBlock(
                                                                        required=True
                                                                    ),
                                                                )
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "image",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "content_image",
                                                                    wagtail.images.blocks.ImageChooserBlock(
                                                                        required=True
                                                                    ),
                                                                ),
                                                                (
                                                                    "alt_text",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text="Only leave this blank if the image is decorative.",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "caption",
                                                                    wagtail.blocks.CharBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "grey_panel",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "label",
                                                                    wagtail.blocks.CharBlock(
                                                                        label="heading",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "heading_level",
                                                                    wagtail.blocks.IntegerBlock(
                                                                        default=3,
                                                                        help_text="The heading level affects users with screen readers. Ignore this if there is no heading. Default=3, Min=2, Max=4.",
                                                                        max_value=4,
                                                                        min_value=2,
                                                                    ),
                                                                ),
                                                                (
                                                                    "body",
                                                                    wagtail.blocks.RichTextBlock(
                                                                        required=True
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "warning_callout",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "title",
                                                                    wagtail.blocks.CharBlock(
                                                                        default="Important",
                                                                        required=True,
                                                                    ),
                                                                ),
                                                                (
                                                                    "heading_level",
                                                                    wagtail.blocks.IntegerBlock(
                                                                        default=3,
                                                                        help_text="The heading level affects users with screen readers. Default=3, Min=2, Max=4.",
                                                                        max_value=4,
                                                                        min_value=2,
                                                                        required=True,
                                                                    ),
                                                                ),
                                                                (
                                                                    "body",
                                                                    wagtail.blocks.RichTextBlock(
                                                                        required=True
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "summary_list",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "rows",
                                                                    wagtail.blocks.ListBlock(
                                                                        wagtailnhsukfrontend.blocks.SummaryListRowBlock
                                                                    ),
                                                                ),
                                                                (
                                                                    "no_border",
                                                                    wagtail.blocks.BooleanBlock(
                                                                        default=False,
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "table",
                                                        modules.core.blocks.TableBlock(),
                                                    ),
                                                ],
                                                required=True,
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "grey_panel",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.CharBlock(
                                                label="heading", required=False
                                            ),
                                        ),
                                        (
                                            "heading_level",
                                            wagtail.blocks.IntegerBlock(
                                                default=3,
                                                help_text="The heading level affects users with screen readers. Ignore this if there is no heading. Default=3, Min=2, Max=4.",
                                                max_value=4,
                                                min_value=2,
                                            ),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.RichTextBlock(
                                                required=True
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "inset_text",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "body",
                                            wagtail.blocks.RichTextBlock(
                                                required=True
                                            ),
                                        )
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "panel_list",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "panels",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "left_panel",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "label",
                                                                        wagtail.blocks.CharBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "heading_level",
                                                                        wagtail.blocks.IntegerBlock(
                                                                            default=3,
                                                                            help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=4.",
                                                                            max_value=4,
                                                                            min_value=2,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "body",
                                                                        wagtail.blocks.RichTextBlock(
                                                                            required=True
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "right_panel",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "label",
                                                                        wagtail.blocks.CharBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "heading_level",
                                                                        wagtail.blocks.IntegerBlock(
                                                                            default=3,
                                                                            help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=4.",
                                                                            max_value=4,
                                                                            min_value=2,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "body",
                                                                        wagtail.blocks.RichTextBlock(
                                                                            required=True
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        )
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "promo_group",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "column",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("one-half", "One-half"),
                                                    ("one-third", "One-third"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "size",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("", "Default"),
                                                    ("small", "Small"),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "heading_level",
                                            wagtail.blocks.IntegerBlock(
                                                default=3,
                                                help_text="The heading level affects users with screen readers. Default=3, Min=2, Max=4.",
                                                max_value=4,
                                                min_value=2,
                                            ),
                                        ),
                                        (
                                            "promos",
                                            wagtail.blocks.ListBlock(
                                                modules.core.blocks.BasePromoBlock
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "warning_callout",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                default="Important", required=True
                                            ),
                                        ),
                                        (
                                            "heading_level",
                                            wagtail.blocks.IntegerBlock(
                                                default=3,
                                                help_text="The heading level affects users with screen readers. Default=3, Min=2, Max=4.",
                                                max_value=4,
                                                min_value=2,
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.RichTextBlock(
                                                required=True
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "table",
                                modules.core.blocks.TableBlock(group=" NHS Components"),
                            ),
                            (
                                "panel_table",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("title", wagtail.blocks.CharBlock()),
                                        ("table", modules.core.blocks.TableBlock()),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                            (
                                "action_link",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "text",
                                            wagtail.blocks.CharBlock(
                                                label="Link text", required=True
                                            ),
                                        ),
                                        (
                                            "external_url",
                                            wagtail.blocks.URLBlock(
                                                label="URL", required=True
                                            ),
                                        ),
                                        (
                                            "new_window",
                                            wagtail.blocks.BooleanBlock(
                                                label="Open in new window",
                                                required=False,
                                            ),
                                        ),
                                    ],
                                    group=" NHS Components",
                                ),
                            ),
                        ],
                        blank=True,
                        verbose_name="Body blocks",
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("alt_text", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "fb_og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facebook OG image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.NHSXImage",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="casestudypage_hero_image",
                        to="images.NHSXImage",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="CaseStudyTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
            ],
            options={
                "verbose_name": "case study tag",
                "verbose_name_plural": "case study tags",
            },
        ),
        migrations.CreateModel(
            name="CaseStudyTags",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="case_studies.CaseStudyPage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_case_studies",
                        to="case_studies.CaseStudyTag",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="casestudypage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="case_studies.CaseStudyTags",
                to="case_studies.CaseStudyTag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="casestudypage",
            name="twitter_card_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Twitter card image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.NHSXImage",
            ),
        ),
    ]
