# Generated by Django 3.0.4 on 2020-07-13 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0026_auto_20200713_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiLabHomePage',
            fields=[
                ('sectionpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.SectionPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.sectionpage',),
        ),
    ]
