# Generated by Django 3.0.4 on 2020-07-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiLabUseCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
