# Generated by Django 3.0.4 on 2020-07-14 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_auto_20200713_1535"),
        ("ai_lab", "0002_ailabusecase"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiLabCaseStudy",
            fields=[
                (
                    "articlepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.ArticlePage",
                    ),
                ),
                (
                    "use_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ai_lab.AiLabUseCase",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("core.articlepage", models.Model),
        ),
    ]
