# Generated by Django 3.0.4 on 2020-07-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lab', '0004_ailabresourceindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ailabusecase',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
