# Generated by Django 3.0.4 on 2020-07-20 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_auto_20200713_1535"),
        ("ai_lab", "0007_ailabresourceindexpage_sub_head"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiLabAdoptIndexPage",
            fields=[
                (
                    "sectionpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.SectionPage",
                    ),
                ),
                (
                    "summary_title",
                    models.CharField(
                        help_text="The title that will appear on the resource index page",
                        max_length=100,
                    ),
                ),
                (
                    "summary_body",
                    models.CharField(
                        help_text="The description that will appear on the resource index page",
                        max_length=255,
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("core.sectionpage",),
        ),
        migrations.CreateModel(
            name="AiLabDevelopIndexPage",
            fields=[
                (
                    "sectionpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.SectionPage",
                    ),
                ),
                (
                    "summary_title",
                    models.CharField(
                        help_text="The title that will appear on the resource index page",
                        max_length=100,
                    ),
                ),
                (
                    "summary_body",
                    models.CharField(
                        help_text="The description that will appear on the resource index page",
                        max_length=255,
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("core.sectionpage",),
        ),
        migrations.CreateModel(
            name="AiLabUnderstandResourceIndexPage",
            fields=[
                (
                    "sectionpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.SectionPage",
                    ),
                ),
                (
                    "summary_title",
                    models.CharField(
                        help_text="The title that will appear on the resource index page",
                        max_length=100,
                    ),
                ),
                (
                    "summary_body",
                    models.CharField(
                        help_text="The description that will appear on the resource index page",
                        max_length=255,
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("core.sectionpage",),
        ),
        migrations.RemoveField(model_name="ailabcasestudy", name="use_case",),
        migrations.RemoveField(model_name="ailabexternalresource", name="use_case",),
        migrations.DeleteModel(name="AiLabUseCase",),
    ]
