# Generated by Django 3.0.4 on 2020-07-20 11:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("wagtailforms", "0004_add_verbose_name_plural"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0026_auto_20200713_1535"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        ("wagtailsearchpromotions", "0002_capitalizeverbose"),
        ("ai_lab", "0008_auto_20200720_1105"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AiLabUnderstandResourceIndexPage",
            new_name="AiLabUnderstandIndexPage",
        ),
    ]
