# Generated by Django 3.0.4 on 2020-07-20 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_auto_20200713_1535"),
        ("images", "0001_initial"),
        ("ai_lab", "0011_auto_20200720_1435_squashed_0012_auto_20200720_1536"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiLabReport",
            fields=[
                (
                    "articlepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.ArticlePage",
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.NHSXImage",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("core.articlepage", models.Model),
        ),
        migrations.CreateModel(
            name="AiLabGuidance",
            fields=[
                (
                    "articlepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.ArticlePage",
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.NHSXImage",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("core.articlepage", models.Model),
        ),
    ]
