# Generated by Django 3.0.4 on 2020-07-20 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("ai_lab", "0012_ailabguidance_ailabreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="ailabcasestudy",
            name="download",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.NHSXDocument",
            ),
        ),
        migrations.AddField(
            model_name="ailabexternalresource",
            name="download",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.NHSXDocument",
            ),
        ),
        migrations.AddField(
            model_name="ailabguidance",
            name="download",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.NHSXDocument",
            ),
        ),
        migrations.AddField(
            model_name="ailabreport",
            name="download",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.NHSXDocument",
            ),
        ),
    ]
