# Generated by Django 3.0.4 on 2020-07-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_lab", "0013_auto_20200720_2014"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ailabcasestudy", options={"verbose_name": "AI Lab - Case Study"},
        ),
        migrations.AlterModelOptions(
            name="ailabexternalresource",
            options={"verbose_name": "AI Lab - External Resource"},
        ),
        migrations.AlterModelOptions(
            name="ailabguidance", options={"verbose_name": "AI Lab - Guidance"},
        ),
        migrations.AlterModelOptions(
            name="ailabreport", options={"verbose_name": "AI Lab - Report"},
        ),
    ]
