# Generated by Django 3.0.4 on 2020-07-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_lab", "0014_auto_20200720_2034"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiLabTopic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("slug", models.SlugField(max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(name="ailabcasestudy", options={},),
        migrations.AlterModelOptions(name="ailabexternalresource", options={},),
        migrations.AlterModelOptions(name="ailabguidance", options={},),
        migrations.AlterModelOptions(name="ailabreport", options={},),
    ]
