# Generated by Django 3.0.4 on 2020-07-21 15:41

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("ai_lab", "0015_auto_20200721_1001"),
    ]

    operations = [
        migrations.AddField(
            model_name="ailabcasestudy",
            name="topics",
            field=modelcluster.fields.ParentalManyToManyField(
                related_name="pages_ailabcasestudy", to="ai_lab.AiLabTopic"
            ),
        ),
        migrations.AddField(
            model_name="ailabexternalresource",
            name="topics",
            field=modelcluster.fields.ParentalManyToManyField(
                related_name="pages_ailabexternalresource", to="ai_lab.AiLabTopic"
            ),
        ),
        migrations.AddField(
            model_name="ailabguidance",
            name="topics",
            field=modelcluster.fields.ParentalManyToManyField(
                related_name="pages_ailabguidance", to="ai_lab.AiLabTopic"
            ),
        ),
        migrations.AddField(
            model_name="ailabreport",
            name="topics",
            field=modelcluster.fields.ParentalManyToManyField(
                related_name="pages_ailabreport", to="ai_lab.AiLabTopic"
            ),
        ),
    ]
