# Generated by Django 3.0.4 on 2020-07-22 11:47

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("ai_lab", "0016_auto_20200721_1541"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ailabtopic",
            options={
                "verbose_name": "AI Lab Topic",
                "verbose_name_plural": "AI Lab Topics",
            },
        ),
        migrations.AlterField(
            model_name="ailabcasestudy",
            name="topics",
            field=modelcluster.fields.ParentalManyToManyField(to="ai_lab.AiLabTopic"),
        ),
        migrations.AlterField(
            model_name="ailabexternalresource",
            name="topics",
            field=modelcluster.fields.ParentalManyToManyField(to="ai_lab.AiLabTopic"),
        ),
        migrations.AlterField(
            model_name="ailabguidance",
            name="topics",
            field=modelcluster.fields.ParentalManyToManyField(to="ai_lab.AiLabTopic"),
        ),
        migrations.AlterField(
            model_name="ailabreport",
            name="topics",
            field=modelcluster.fields.ParentalManyToManyField(to="ai_lab.AiLabTopic"),
        ),
    ]
