# Generated by Django 3.0.4 on 2020-07-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_lab", "0018_auto_20200724_1308"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ailabcasestudy",
            options={
                "verbose_name": "Case Study",
                "verbose_name_plural": "Case Studies",
            },
        ),
        migrations.AlterModelOptions(
            name="ailabexternalresource",
            options={
                "verbose_name": "External Resource",
                "verbose_name_plural": "External Resources",
            },
        ),
        migrations.AlterModelOptions(
            name="ailabguidance",
            options={"verbose_name": "Guidance", "verbose_name_plural": "Guidance"},
        ),
        migrations.AlterModelOptions(
            name="ailabreport",
            options={"verbose_name": "Report", "verbose_name_plural": "Reports"},
        ),
    ]
