# Generated by Django 3.0.4 on 2020-07-29 12:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("ai_lab", "0019_auto_20200727_1532"),
    ]

    operations = [
        migrations.AddField(
            model_name="ailabcasestudy",
            name="featured_resources",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.core.blocks.PageChooserBlock(
                            label="Page",
                            page_type=["blog_posts.BlogPost"],
                            required=True,
                        ),
                    )
                ],
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="ailabexternalresource",
            name="featured_resources",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.core.blocks.PageChooserBlock(
                            label="Page",
                            page_type=["blog_posts.BlogPost"],
                            required=True,
                        ),
                    )
                ],
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="ailabguidance",
            name="featured_resources",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.core.blocks.PageChooserBlock(
                            label="Page",
                            page_type=["blog_posts.BlogPost"],
                            required=True,
                        ),
                    )
                ],
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="ailabreport",
            name="featured_resources",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.core.blocks.PageChooserBlock(
                            label="Page",
                            page_type=["blog_posts.BlogPost"],
                            required=True,
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
