# Generated by Django 3.0.4 on 2020-07-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_lab", "0022_auto_20200729_0739"),
        ("ai_lab", "0020_auto_20200729_1229"),
    ]

    operations = []
