# Generated by Django 3.0.7 on 2020-10-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_lab", "0029_auto_20201006_1338"),
    ]

    operations = [
        migrations.AddField(
            model_name="ailabresourcecollection",
            name="summary",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
