# Generated by Django 3.0.7 on 2020-12-10 13:22

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        ("documents", "0001_initial"),
        ("ai_lab", "0033_auto_20201113_1110"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiLabInternalResource",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                (
                    "featured_resources",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "link",
                                wagtail.core.blocks.PageChooserBlock(
                                    label="Page",
                                    page_type=[
                                        "ai_lab.AiLabCaseStudy",
                                        "ai_lab.AiLabGuidance",
                                        "ai_lab.AiLabReport",
                                        "ai_lab.AiLabExternalResource",
                                    ],
                                    required=True,
                                ),
                            )
                        ],
                        blank=True,
                    ),
                ),
                (
                    "download",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documents.NHSXDocument",
                    ),
                ),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.NHSXImage",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "topics",
                    modelcluster.fields.ParentalManyToManyField(to="ai_lab.AiLabTopic"),
                ),
            ],
            options={
                "verbose_name": "Internal Resource",
                "verbose_name_plural": "Internal Resources",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
