# Generated by Django 3.0.4 on 2020-04-08 12:22

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pagetag'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('news', '0005_news_canonical_rel'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.PageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
