# Generated by Django 3.0.4 on 2020-04-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200409_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsindexpage',
            name='headline',
        ),
    ]
