# Generated by Django 3.0.4 on 2020-04-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0009_auto_20200409_1210"),
        ("news", "0009_remove_newsindexpage_headline"),
    ]

    operations = []
