# Generated by Django 3.0.4 on 2020-04-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0012_auto_20200409_1452"),
        ("news", "0009_auto_20200414_0913"),
    ]

    operations = []
