# Generated by Django 3.0.7 on 2020-09-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ig_guidance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="igtemplate", options={"verbose_name": "Template"},
        ),
    ]
