# Generated by Django 3.0.7 on 2020-09-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ig_guidance', '0005_internalguidance_introduction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalguidance',
            options={'verbose_name': 'Panel Guidance'},
        ),
    ]
